#!/bin/bash
#
# IBM Omni driver
# Copyright (c) International Business Machines Corp., 2000
#
# This library is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
# the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

source setit

rm -rf CUPS/PPDs/
rm -rf Foomatic/foomatic-db/

NEWDESTDIR=
if [ "$#" = "1" ]; then
	if test ${1:0:1} = "/"; then
		NEWDESTDIR=$1
	else
		NEWDESTDIR=`pwd`/$1
	fi
	rm -rf ${NEWDESTDIR};
        mkdir -p ${NEWDESTDIR}
fi

(cd CUPS; make generateBuildPPDs)

make DESTDIR=${NEWDESTDIR} install

(cd Foomatic; make DESTDIR=${NEWDESTDIR} localInstall)

if [ "$#" = "0" ]; then
	make localInstall
fi
