#!/bin/bash
#
# IBM Omni driver
# Copyright (c) International Business Machines Corp., 2000
#
# This library is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
# the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

cd ..

if (($# == 0)) ;
then
	source ./devicesXML.list
	DEVICES=$DEVICELIST
else
	DEVICES="$@"
fi

FILE1=/tmp/$$.1
FILE2=/tmp/$$.2
rm $FILE1 $FILE2 2> /dev/null

for i in $DEVICES ;
do
        (
        DIR="`echo $i | sed -e 's/~//g' -e 's/_/\\\\ /g'`"
	cd "`echo $i | sed -e 's/~//g' -e 's/_/ /g'`"

        grep \<Blitter\> *.xml | sed -e 's/<\/*Blitter>//g' -e 's/^.*:/:/' -e "s/^:\ */$DIR\\//" -e 's/ /\\ /g' -e 's/^/vs /' >> $FILE1 2>&1
        )
done

cat $FILE1 | sort | uniq > $FILE2

export VSLICKXNOPLUSNEWMSG=1
vs&

sh -c "`cat $FILE2`"

rm $FILE1 $FILE2 2> /dev/null
