#!/bin/bash
cd test2
find . -name \*.new -exec rm {} \;
./doit || exit
echo "doit2: done!"
for i in *.new; do
	if test -f "$i"; then
		echo "======================================================================"
		cat "$i"
		echo "======================================================================"
	fi
done
