#!/bin/bash
cd test3
find . -name \*.new -exec rm {} \;
./doit || exit
echo "doit3: done!"
for i in *.new; do
	if test -f "$i"; then
		echo "======================================================================"
		cat "$i"
		echo "======================================================================"
	fi
done
