#!/bin/bash
#
# IBM Omni driver
# Copyright (c) International Business Machines Corp., 2000
#
# This library is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
# the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

FROMDIR="../../XMLParser"

#if [ "Minimal Device Commands.xml"     -ot ${FROMDIR}"/Minimal Device Commands.xml"     ]; then echo 'copying "Minimal Device Commands.xml"';     cp ${FROMDIR}"/Minimal Device Commands.xml"     .; fi
#if [ "Minimal Device Forms.xml"        -ot ${FROMDIR}"/Minimal Device Forms.xml"        ]; then echo 'copying "Minimal Device Forms.xml"';        cp ${FROMDIR}"/Minimal Device Forms.xml"        .; fi
#if [ "Minimal Device Medias.xml"       -ot ${FROMDIR}"/Minimal Device Medias.xml"       ]; then echo 'copying "Minimal Device Medias.xml"';       cp ${FROMDIR}"/Minimal Device Medias.xml"       .; fi
#if [ "Minimal Device Orientations.xml" -ot ${FROMDIR}"/Minimal Device Orientations.xml" ]; then echo 'copying "Minimal Device Orientations.xml"'; cp ${FROMDIR}"/Minimal Device Orientations.xml" .; fi
#if [ "Minimal Device PrintModes.xml"   -ot ${FROMDIR}"/Minimal Device PrintModes.xml"   ]; then echo 'copying "Minimal Device PrintModes.xml"';   cp ${FROMDIR}"/Minimal Device PrintModes.xml"   .; fi
#if [ "Minimal Device Resolutions.xml"  -ot ${FROMDIR}"/Minimal Device Resolutions.xml"  ]; then echo 'copying "Minimal Device Resolutions.xml"';  cp ${FROMDIR}"/Minimal Device Resolutions.xml"  .; fi
#if [ "Minimal Device Trays.xml"        -ot ${FROMDIR}"/Minimal Device Trays.xml"        ]; then echo 'copying "Minimal Device Trays.xml"';        cp ${FROMDIR}"/Minimal Device Trays.xml"        .; fi
#if [ "Minimal Device.xml"              -ot ${FROMDIR}"/Minimal Device.xml"              ]; then echo 'copying "Minimal Device.xml"';              cp ${FROMDIR}"/Minimal Device.xml"              .; fi

../OmniEditDevice.py --gladePath ".." "Minimal Device.xml"
